# Broadcasting Basics

## Broadcasting between a 2D and 1D array

In [4]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

result = A + b

print("2D Array A:")
print(A)

print("1D Array b:")
print(b)

print("Result of A + b:")
print(result)

2D Array A:
[[1 2 3]
 [4 5 6]]
1D Array b:
[10 20 30]
Result of A + b:
[[11 22 33]
 [14 25 36]]


# Broadcast a 1D row vector across a 2D matrix

In [5]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row = np.array([10, 20, 30])

addition = matrix + row
multiplication = matrix * row

print("Matrix:")
print(matrix)

print("Row Vector:")
print(row)

print("\nAfter Addition:")
print(addition)

print("\nAfter Multiplication:")
print(multiplication)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row Vector:
[10 20 30]

After Addition:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

After Multiplication:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


#

# Advanced Broadcasting with Higher Dimensions

## Multiply Two 3D Arrays Using Complex Broadcasting

In [6]:
import numpy as np

A = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 1, 2)
B = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2, 1)

result = A * B

print("Array A:")
print(A)
print("Shape of A:", A.shape)

print("\nArray B:")
print(B)
print("Shape of B:", B.shape)

print("\nResult after Broadcasting Multiplication:")
print(result)
print("Shape of Result:", result.shape)

Array A:
[[[1 2]]

 [[3 4]]

 [[5 6]]]
Shape of A: (3, 1, 2)

Array B:
[[[10]
  [20]]

 [[30]
  [40]]

 [[50]
  [60]]]
Shape of B: (3, 2, 1)

Result after Broadcasting Multiplication:
[[[ 10  20]
  [ 20  40]]

 [[ 90 120]
  [120 160]]

 [[250 300]
  [300 360]]]
Shape of Result: (3, 2, 2)


## Verify Broadcasting Compatibility Rules

In [7]:
import numpy as np

def check_broadcast(shape1, shape2):
    try:
        result = np.broadcast_shapes(shape1, shape2)
        print(f"{shape1} and {shape2} -> Compatible")
        print("Result shape:", result)
    except ValueError:
        print(f"{shape1} and {shape2} -> Not Compatible")

print("Broadcasting Compatibility:")

check_broadcast((3, 4), (4,))
check_broadcast((3, 4), (1, 4))
check_broadcast((3, 4), (3, 1))
check_broadcast((3, 4), (2,))

print("\nActual Broadcasting Example:")

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print("A + B:")
print(A + B)

Broadcasting Compatibility:
(3, 4) and (4,) -> Compatible
Result shape: (3, 4)
(3, 4) and (1, 4) -> Compatible
Result shape: (3, 4)
(3, 4) and (3, 1) -> Compatible
Result shape: (3, 4)
(3, 4) and (2,) -> Not Compatible

Actual Broadcasting Example:
A + B:
[[11 22 33]
 [14 25 36]]


#

# Creating Series from Various Sources

## Create a Series from a List With and Without Custom Index

In [1]:
import pandas as pd

# Series without custom index
s1 = pd.Series([10, 20, 30, 40])

print("Series without custom index:")
print(s1)

# Series with custom index
s2 = pd.Series([10, 20, 30, 40],
               index=["A", "B", "C", "D"])

print("\nSeries with custom index:")
print(s2)

ImportError: Unable to import required dependency numpy. Please see the traceback for details.

## Create a Series from a NumPy Array and Verify Data Linkage

In [1]:
import numpy as np
import pandas as pd

# Create NumPy array
arr = np.array([10, 20, 30, 40])

# Create Series from array
s = pd.Series(arr)

print("Original NumPy Array:")
print(arr)

print("\nSeries:")
print(s)

# Change NumPy array
arr[0] = 100

print("\nAfter changing NumPy array:")
print("Array:", arr)
print("Series:")
print(s)

Original NumPy Array:
[10 20 30 40]

Series:
0    10
1    20
2    30
3    40
dtype: int64

After changing NumPy array:
Array: [100  20  30  40]
Series:
0    10
1    20
2    30
3    40
dtype: int64
