# Broadcasting Basics

## Broadcasting between a 2D and 1D array

In [4]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

result = A + b

print("2D Array A:")
print(A)

print("1D Array b:")
print(b)

print("Result of A + b:")
print(result)

2D Array A:
[[1 2 3]
 [4 5 6]]
1D Array b:
[10 20 30]
Result of A + b:
[[11 22 33]
 [14 25 36]]


# Broadcast a 1D row vector across a 2D matrix

In [5]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row = np.array([10, 20, 30])

addition = matrix + row
multiplication = matrix * row

print("Matrix:")
print(matrix)

print("Row Vector:")
print(row)

print("\nAfter Addition:")
print(addition)

print("\nAfter Multiplication:")
print(multiplication)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row Vector:
[10 20 30]

After Addition:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

After Multiplication:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


#

# Advanced Broadcasting with Higher Dimensions

## Multiply Two 3D Arrays Using Complex Broadcasting

In [6]:
import numpy as np

A = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 1, 2)
B = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2, 1)

result = A * B

print("Array A:")
print(A)
print("Shape of A:", A.shape)

print("\nArray B:")
print(B)
print("Shape of B:", B.shape)

print("\nResult after Broadcasting Multiplication:")
print(result)
print("Shape of Result:", result.shape)

Array A:
[[[1 2]]

 [[3 4]]

 [[5 6]]]
Shape of A: (3, 1, 2)

Array B:
[[[10]
  [20]]

 [[30]
  [40]]

 [[50]
  [60]]]
Shape of B: (3, 2, 1)

Result after Broadcasting Multiplication:
[[[ 10  20]
  [ 20  40]]

 [[ 90 120]
  [120 160]]

 [[250 300]
  [300 360]]]
Shape of Result: (3, 2, 2)


## Verify Broadcasting Compatibility Rules

In [7]:
import numpy as np

def check_broadcast(shape1, shape2):
    try:
        result = np.broadcast_shapes(shape1, shape2)
        print(f"{shape1} and {shape2} -> Compatible")
        print("Result shape:", result)
    except ValueError:
        print(f"{shape1} and {shape2} -> Not Compatible")

print("Broadcasting Compatibility:")

check_broadcast((3, 4), (4,))
check_broadcast((3, 4), (1, 4))
check_broadcast((3, 4), (3, 1))
check_broadcast((3, 4), (2,))

print("\nActual Broadcasting Example:")

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print("A + B:")
print(A + B)

Broadcasting Compatibility:
(3, 4) and (4,) -> Compatible
Result shape: (3, 4)
(3, 4) and (1, 4) -> Compatible
Result shape: (3, 4)
(3, 4) and (3, 1) -> Compatible
Result shape: (3, 4)
(3, 4) and (2,) -> Not Compatible

Actual Broadcasting Example:
A + B:
[[11 22 33]
 [14 25 36]]


#

# Creating Series from Various Sources

## Create a Series from a List With and Without Custom Index

In [2]:
import pandas as pd

# Series without custom index
s1 = pd.Series([10, 20, 30, 40])

print("Series without custom index:")
print(s1)

# Series with custom index
s2 = pd.Series([10, 20, 30, 40],
               index=["A", "B", "C", "D"])

print("\nSeries with custom index:")
print(s2)

Series without custom index:
0    10
1    20
2    30
3    40
dtype: int64

Series with custom index:
A    10
B    20
C    30
D    40
dtype: int64


## Create a Series from a NumPy Array and Verify Data Linkage

In [11]:
import numpy as np
import pandas as pd

# Create NumPy array
arr = np.array([10, 20, 30, 40])

# Create Series from array
s = pd.Series(arr)

print("Original NumPy Array:")
print(arr)

print("\nSeries:")
print(s)

# Change NumPy array
arr[0] = 100

print("\nAfter changing NumPy array:")
print("Array:", arr)
print("Series:")
print(s)

Original NumPy Array:
[10 20 30 40]

Series:
0    10
1    20
2    30
3    40
dtype: int64

After changing NumPy array:
Array: [100  20  30  40]
Series:
0    10
1    20
2    30
3    40
dtype: int64


## Create a Series from a Dictionary With Custom Index

In [3]:
import pandas as pd

# Create dictionary
data = {
    "A": 10,
    "B": 20,
    "C": 30
}

# Series using dictionary
s1 = pd.Series(data)

print("Series from dictionary:")
print(s1)

# Custom index with a missing key
s2 = pd.Series(data, index=["A", "B", "C", "D"])

print("\nSeries with custom index:")
print(s2)

Series from dictionary:
A    10
B    20
C    30
dtype: int64

Series with custom index:
A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64


#

# Indexing and Value Access

## Access Series Values Using Position and Label Indexing

In [4]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50],
              index=["A", "B", "C", "D", "E"])

print("Series:")
print(s)

# Position-based indexing
print("\nValue at position 0:", s.iloc[0])
print("Value at position 2:", s.iloc[2])

# Label-based indexing
print("\nValue with label A:", s.loc["A"])
print("Value with label C:", s.loc["C"])

# Position-based slicing
print("\nPosition slicing:")
print(s.iloc[1:4])

# Label-based slicing
print("\nLabel slicing:")
print(s.loc["B":"D"])

# Selecting multiple labels
print("\nSelected labels:")
print(s.loc[["A", "C", "E"]])

Series:
A    10
B    20
C    30
D    40
E    50
dtype: int64

Value at position 0: 10
Value at position 2: 30

Value with label A: 10
Value with label C: 30

Position slicing:
B    20
C    30
D    40
dtype: int64

Label slicing:
B    20
C    30
D    40
dtype: int64

Selected labels:
A    10
C    30
E    50
dtype: int64


## Assign New Values to Series Elements

In [5]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50],
              index=["A", "B", "C", "D", "E"])

print("Original Series:")
print(s)

# Update using position
s.iloc[0] = 100

# Update using label
s.loc["C"] = 300

print("\nAfter updating individual values:")
print(s)

# Update selected labels
s.loc[["B", "D"]] = [200, 400]

print("\nAfter updating selected labels:")
print(s)

# Update a slice
s.iloc[1:3] = [250, 350]

print("\nAfter updating a slice:")
print(s)

Original Series:
A    10
B    20
C    30
D    40
E    50
dtype: int64

After updating individual values:
A    100
B     20
C    300
D     40
E     50
dtype: int64

After updating selected labels:
A    100
B    200
C    300
D    400
E     50
dtype: int64

After updating a slice:
A    100
B    250
C    350
D    400
E     50
dtype: int64


#

# Mathematical and Conditional Operations

## Filter Series Values Using a Conditional Expression

In [6]:
import pandas as pd

s = pd.Series([5, 10, 15, 20, 25],
              index=["A", "B", "C", "D", "E"])

print("Original Series:")
print(s)

# Filter values greater than 8
print("\nValues greater than 8:")
print(s[s > 8])

# Multiple conditions
print("\nValues greater than 8 and less than 25:")
print(s[(s > 8) & (s < 25)])

Original Series:
A     5
B    10
C    15
D    20
E    25
dtype: int64

Values greater than 8:
B    10
C    15
D    20
E    25
dtype: int64

Values greater than 8 and less than 25:
B    10
C    15
D    20
dtype: int64


## Apply Arithmetic and Mathematical Functions on Series

In [7]:
import pandas as pd
import numpy as np

s = pd.Series([2, 4, 8, 16, 32])

print("Original Series:")
print(s)

# Element-wise division
print("\nSeries divided by 2:")
print(s / 2)

# Addition
print("\nSeries + 5:")
print(s + 5)

# NumPy logarithm function
print("\nNatural logarithm:")
print(np.log(s))

print("\nType of result:", type(s / 2))
print("Shape of result:", (s / 2).shape)

Original Series:
0     2
1     4
2     8
3    16
4    32
dtype: int64

Series divided by 2:
0     1.0
1     2.0
2     4.0
3     8.0
4    16.0
dtype: float64

Series + 5:
0     7
1     9
2    13
3    21
4    37
dtype: int64

Natural logarithm:
0    0.693147
1    1.386294
2    2.079442
3    2.772589
4    3.465736
dtype: float64

Type of result: <class 'pandas.Series'>
Shape of result: (5,)


#

# Evaluating and Counting Series Data

## Check Duplicate, Unique, and Value Counts in a Series

In [8]:
import pandas as pd

s = pd.Series([10, 20, 10, 30, 20, 10, 40, 30])

print("Original Series:")
print(s)

# Get unique values
print("\nUnique values:")
print(s.unique())

# Count frequency of each value
print("\nValue counts:")
print(s.value_counts())

# Check for duplicates
print("\nDuplicate values:")
print(s[s.duplicated()])

Original Series:
0    10
1    20
2    10
3    30
4    20
5    10
6    40
7    30
dtype: int64

Unique values:
[10 20 30 40]

Value counts:
10    3
20    2
30    2
40    1
Name: count, dtype: int64

Duplicate values:
2    10
4    20
5    10
7    30
dtype: int64


## Evaluate Element Membership Using isin()

In [9]:
import pandas as pd

s = pd.Series([10, 20, 30, 40, 50])

print("Original Series:")
print(s)

# Check membership
result = s.isin([20, 40, 60])

print("\nMembership result:")
print(result)

# Extract matching elements
print("\nMatching elements:")
print(s[result])

# Combine isin() with another condition
print("\nMatching elements greater than 20:")
print(s[s.isin([20, 40, 50]) & (s > 20)])

Original Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Membership result:
0    False
1     True
2    False
3     True
4    False
dtype: bool

Matching elements:
1    20
3    40
dtype: int64

Matching elements greater than 20:
3    40
4    50
dtype: int64


#

# Handling Missing Data (NaNs)

## Create a Series with NaN Values and Detect Them

In [10]:
import pandas as pd
import numpy as np

# Create Series with NaN values
s = pd.Series([10, 20, np.nan, 40, np.nan, 60])

print("Original Series:")
print(s)

# Detect missing values
print("\nMissing values using isnull():")
print(s.isnull())

# Detect non-missing values
print("\nNon-missing values using notnull():")
print(s.notnull())

# Print incomplete records
print("\nIncomplete records:")
print(s[s.isnull()])

# Print complete records
print("\nComplete records:")
print(s[s.notnull()])

Original Series:
0    10.0
1    20.0
2     NaN
3    40.0
4     NaN
5    60.0
dtype: float64

Missing values using isnull():
0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

Non-missing values using notnull():
0     True
1     True
2    False
3     True
4    False
5     True
dtype: bool

Incomplete records:
2   NaN
4   NaN
dtype: float64

Complete records:
0    10.0
1    20.0
3    40.0
5    60.0
dtype: float64
