# 84

In [1]:
import numpy as np

# Create NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

# Addition
print("\nAddition:")
print(arr + 5)

# Subtraction
print("\nSubtraction:")
print(arr - 5)

# Multiplication
print("\nMultiplication:")
print(arr * 5)

# Division
print("\nDivision:")
print(arr / 5)

Original Array:
[10 20 30 40 50]

Addition:
[15 25 35 45 55]

Subtraction:
[ 5 15 25 35 45]

Multiplication:
[ 50 100 150 200 250]

Division:
[ 2.  4.  6.  8. 10.]


#

# 85

In [2]:
import numpy as np

# Create two arrays
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Array A:")
print(a)

print("\nArray B:")
print(b)

# Addition
print("\nAddition:")
print(a + b)

# Subtraction
print("\nSubtraction:")
print(a - b)

# Multiplication
print("\nMultiplication:")
print(a * b)

# Division
print("\nDivision:")
print(a / b)

Array A:
[10 20 30 40]

Array B:
[2 4 5 8]

Addition:
[12 24 35 48]

Subtraction:
[ 8 16 25 32]

Multiplication:
[ 20  80 150 320]

Division:
[5. 5. 6. 5.]


#

# 86

In [3]:
import numpy as np

# Create 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Original Array:")
print(arr)

# Scalar broadcasting
print("\nArray + 5:")
print(arr + 5)

print("\nArray - 5:")
print(arr - 5)

print("\nArray * 2:")
print(arr * 2)

print("\nArray / 2:")
print(arr / 2)

Original Array:
[[10 20 30]
 [40 50 60]]

Array + 5:
[[15 25 35]
 [45 55 65]]

Array - 5:
[[ 5 15 25]
 [35 45 55]]

Array * 2:
[[ 20  40  60]
 [ 80 100 120]]

Array / 2:
[[ 5. 10. 15.]
 [20. 25. 30.]]


#

# 87

In [4]:
import numpy as np

# Create an array
arr = np.array([1, 4, 9, 16, 25])

print("Original Array:")
print(arr)

# Square root
sqrt_result = np.sqrt(arr)

print("\nSquare Root:")
print(sqrt_result)

# Logarithm
log_result = np.log(arr)

print("\nNatural Logarithm:")
print(log_result)

# Sine
sin_result = np.sin(arr)

print("\nSine:")
print(sin_result)

Original Array:
[ 1  4  9 16 25]

Square Root:
[1. 2. 3. 4. 5.]

Natural Logarithm:
[0.         1.38629436 2.19722458 2.77258872 3.21887582]

Sine:
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


#

# 88

In [5]:
import numpy as np

# Create array
arr = np.array([1, 2, 3, 4, 5])

print("Original Array:")
print(arr)

# Calculate sine
sin_result = np.sin(arr)

print("\nSin(Array):")
print(sin_result)

# Multiply array with sin(array)
result = arr * np.sin(arr)

print("\nArray * Sin(Array):")
print(result)

Original Array:
[1 2 3 4 5]

Sin(Array):
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

Array * Sin(Array):
[ 0.84147098  1.81859485  0.42336002 -3.02720998 -4.79462137]
