# 70,71

In [1]:
import numpy as np

# 1D array using list
arr1 = np.array([10, 20, 30, 40, 50])

# 1D array using tuple
arr2 = np.array((1, 2, 3, 4, 5))

# 2D array using nested list
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

# 2D array using nested tuple
arr4 = np.array(((10, 20), (30, 40)))

print("1D Array using List:")
print(arr1)

print("\n1D Array using Tuple:")
print(arr2)

print("\n2D Array using Nested List:")
print(arr3)

print("\n2D Array using Nested Tuple:")
print(arr4)

# Checking type
print("\nType of arr1:", type(arr1))
print("Type of arr3:", type(arr3))

# Checking dimensions
print("Dimension of arr1:", arr1.ndim)
print("Dimension of arr3:", arr3.ndim)

# Checking shape
print("Shape of arr1:", arr1.shape)
print("Shape of arr3:", arr3.shape)

1D Array using List:
[10 20 30 40 50]

1D Array using Tuple:
[1 2 3 4 5]

2D Array using Nested List:
[[1 2 3]
 [4 5 6]]

2D Array using Nested Tuple:
[[10 20]
 [30 40]]

Type of arr1: <class 'numpy.ndarray'>
Type of arr3: <class 'numpy.ndarray'>
Dimension of arr1: 1
Dimension of arr3: 2
Shape of arr1: (5,)
Shape of arr3: (2, 3)


In [2]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Array:")
print(arr)

print("\nShape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Number of Dimensions:", arr.ndim)
print("Item Size:", arr.itemsize)

# Rank = number of dimensions
print("Rank of Array:", arr.ndim)

# Internal buffer
print("\nData attribute:")
print(arr.data)

Array:
[[10 20 30]
 [40 50 60]]

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2
Item Size: 8
Rank of Array: 2

Data attribute:


#

# 72,73,74,75,76

In [3]:
import numpy as np

# Create 3x3 array of zeros
arr = np.zeros((3, 3))

print("3x3 Array of Zeros:")
print(arr)

print("\nData Type:", arr.dtype)
print("Shape:", arr.shape)

# Create zeros with integer data type
arr_int = np.zeros((3, 3), dtype=int)

print("\n3x3 Integer Array of Zeros:")
print(arr_int)

print("Data Type:", arr_int.dtype)

3x3 Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Data Type: float64
Shape: (3, 3)

3x3 Integer Array of Zeros:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Data Type: int64


In [4]:
import numpy as np

# Create 3x3 array of ones
arr = np.ones((3, 3))

print("3x3 Array of Ones:")
print(arr)

# Create 1D array of ones
arr1 = np.ones(5)

print("\n1D Array of Ones:")
print(arr1)

# Create integer array of ones
arr2 = np.ones((3, 3), dtype=int)

print("\n3x3 Integer Array of Ones:")
print(arr2)

3x3 Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1D Array of Ones:
[1. 1. 1. 1. 1.]

3x3 Integer Array of Ones:
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
import numpy as np

# Start, stop
arr1 = np.arange(1, 10)

print("1 to 9:")
print(arr1)

# Start, stop, step
arr2 = np.arange(0, 20, 2)

print("\nEven numbers:")
print(arr2)

# Odd numbers
arr3 = np.arange(1, 20, 2)

print("\nOdd numbers:")
print(arr3)

# Negative step
arr4 = np.arange(10, 0, -1)

print("\nReverse sequence:")
print(arr4)

# Float step
arr5 = np.arange(0, 2, 0.2)

print("\nFloat sequence:")
print(arr5)

1 to 9:
[1 2 3 4 5 6 7 8 9]

Even numbers:
[ 0  2  4  6  8 10 12 14 16 18]

Odd numbers:
[ 1  3  5  7  9 11 13 15 17 19]

Reverse sequence:
[10  9  8  7  6  5  4  3  2  1]

Float sequence:
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [6]:
import numpy as np

# Create 1D array
arr = np.arange(1, 10)

print("1D Array:")
print(arr)

# Reshape into 3x3
new_arr = arr.reshape(3, 3)

print("\n2D Array:")
print(new_arr)

print("\nOriginal Shape:", arr.shape)
print("New Shape:", new_arr.shape)
print("Number of Dimensions:", new_arr.ndim)

1D Array:
[1 2 3 4 5 6 7 8 9]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Original Shape: (9,)
New Shape: (3, 3)
Number of Dimensions: 2


In [7]:
import numpy as np

# Generate 5 evenly spaced values
arr1 = np.linspace(0, 10, 5)

print("5 Evenly Spaced Values:")
print(arr1)

# Generate 11 values
arr2 = np.linspace(0, 10, 11)

print("\n11 Evenly Spaced Values:")
print(arr2)

# Generate values between 1 and 5
arr3 = np.linspace(1, 5, 9)

print("\n9 Evenly Spaced Values:")
print(arr3)

5 Evenly Spaced Values:
[ 0.   2.5  5.   7.5 10. ]

11 Evenly Spaced Values:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

9 Evenly Spaced Values:
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
