In [1]:
import numpy as np

## Universal and Mathematical Functions

#

In [2]:
# 87. Apply sin(), sqrt(), and log() on arrays

arr = np.array([1, 4, 9, 16, 25])

sin_result = np.sin(arr)
sqrt_result = np.sqrt(arr)
log_result = np.log(arr)

print("Original Array:")
print(arr)

print("\nSin:")
print(sin_result)

print("\nSquare Root:")
print(sqrt_result)

print("\nLog:")
print(log_result)

Original Array:
[ 1  4  9 16 25]

Sin:
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]

Square Root:
[1. 2. 3. 4. 5.]

Log:
[0.         1.38629436 2.19722458 2.77258872 3.21887582]


#

In [3]:
# 88. Multiply array with sin(array)

arr = np.array([0, 1, 2, 3, 4])

result = arr * np.sin(arr)

print("Original Array:")
print(arr)

print("\nsin(array):")
print(np.sin(arr))

print("\narray * sin(array):")
print(result)

Original Array:
[0 1 2 3 4]

sin(array):
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]

array * sin(array):
[ 0.          0.84147098  1.81859485  0.42336002 -3.02720998]


#
#

## Matrix Operations

#

In [4]:
# 89. Matrix multiplication

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result1 = np.dot(A, B)
result2 = A.dot(B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nUsing np.dot():")
print(result1)

print("\nUsing A.dot():")
print(result2)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Using np.dot():
[[19 22]
 [43 50]]

Using A.dot():
[[19 22]
 [43 50]]


#

In [5]:
# 90. Compare element-wise multiplication and dot product

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

element_wise = A * B
dot_product = np.dot(A, B)

print("Element-wise multiplication:")
print(element_wise)

print("\nDot product:")
print(dot_product)

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Dot product:
[[19 22]
 [43 50]]


#
#

## Aggregate Functions and In-Place Updates

#

In [6]:
# 91. Aggregate functions

arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr1)

print("\nSum:", arr1.sum())
print("Mean:", arr1.mean())
print("Standard Deviation:", arr1.std())
print("Minimum:", arr1.min())
print("Maximum:", arr1.max())


arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print("\n2D Array:")
print(arr2)

print("\nSum:", arr2.sum())
print("Mean:", arr2.mean())
print("Standard Deviation:", arr2.std())
print("Minimum:", arr2.min())
print("Maximum:", arr2.max())

1D Array:
[10 20 30 40 50]

Sum: 150
Mean: 30.0
Standard Deviation: 14.142135623730951
Minimum: 10
Maximum: 50

2D Array:
[[10 20 30]
 [40 50 60]]

Sum: 210
Mean: 35.0
Standard Deviation: 17.07825127659933
Minimum: 10
Maximum: 60


#

In [7]:
# 92. In-place updates

arr = np.array([10, 20, 30, 40])

print("Original Array:")
print(arr)

arr += 5
print("\nAfter += 5:")
print(arr)

arr -= 2
print("\nAfter -= 2:")
print(arr)

arr *= 3
print("\nAfter *= 3:")
print(arr)

Original Array:
[10 20 30 40]

After += 5:
[15 25 35 45]

After -= 2:
[13 23 33 43]

After *= 3:
[ 39  69  99 129]


#
#

## Basic Indexing and Slicing

In [8]:
# 93. Positive and negative indexing

arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)

print("\nFirst element:", arr[0])
print("Second element:", arr[1])
print("Last element:", arr[-1])
print("Second last element:", arr[-2])

Array:
[10 20 30 40 50]

First element: 10
Second element: 20
Last element: 50
Second last element: 40


#

In [12]:
# 94. Index arrays

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

print("\nSelected elements:")
print(arr[[0, 2, 4]])

print("\nUsing positive and negative indexes:")
print(arr[[0, -1, 2]])

Original Array:
[10 20 30 40 50]

Selected elements:
[10 30 50]

Using positive and negative indexes:
[10 50 30]


#

In [11]:
# 95. 2D array indexing

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("2D Array:")
print(arr)

print("\nElement at row 0, column 1:")
print(arr[0, 1])

print("\nElement at row 2, column 2:")
print(arr[2, 2])

print("\nUsing nested indexing:")
print(arr[2][2])

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at row 0, column 1:
20

Element at row 2, column 2:
90

Using nested indexing:
90


#
#

## Advanced Slicing Techniques

#

In [14]:
# 96. Slicing

arr = np.array([10, 20, 30, 40, 50, 60])

print("Original Array:")
print(arr)

slice_arr = arr[1:5]

print("\nSlice:")
print(slice_arr)

slice_arr[:] = 99

print("\nModified Slice:")
print(slice_arr)

print("\nOriginal Array after modifying slice:")
print(arr)

Original Array:
[10 20 30 40 50 60]

Slice:
[20 30 40 50]

Modified Slice:
[99 99 99 99]

Original Array after modifying slice:
[10 99 99 99 99 60]


#

In [15]:
# 97. 2D slicing and assignment

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original Array:")
print(arr)

arr[0:2, 1:3] = 99

print("\nAfter assigning 99:")
print(arr)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After assigning 99:
[[ 1 99 99]
 [ 4 99 99]
 [ 7  8  9]]


#

In [16]:
# 98. Reshape and shape

arr = np.arange(1, 7)

print("Original Array:")
print(arr)

print("\nOriginal Shape:")
print(arr.shape)

new_arr = arr.reshape(2, 3)

print("\nAfter reshape:")
print(new_arr)

print("\nNew Shape:")
print(new_arr.shape)

# Changing shape directly
arr.shape = (2, 3)

print("\nAfter changing shape attribute:")
print(arr)

Original Array:
[1 2 3 4 5 6]

Original Shape:
(6,)

After reshape:
[[1 2 3]
 [4 5 6]]

New Shape:
(2, 3)

After changing shape attribute:
[[1 2 3]
 [4 5 6]]


C:\Users\romil\AppData\Local\Temp\ipykernel_23844\2441155816.py:20: DeprecationWarning: Setting the shape on a NumPy array has been deprecated in NumPy 2.5.
As an alternative, you can create a new view using np.reshape (with copy=False if needed).
  arr.shape = (2, 3)


#
#

## Multidimensional Array Handling

#

In [17]:
# 99. 3D array indexing

arr = np.arange(1, 25).reshape(2, 3, 4)

print("3D Array:")
print(arr)

print("\nUsing comma-separated indexing:")
print(arr[0, 1, 2])

print("\nUsing chained indexing:")
print(arr[0][1][2])

# Modify an element
arr[0, 1, 2] = 100

print("\nAfter modification:")
print(arr)

3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Using comma-separated indexing:
7

Using chained indexing:
7

After modification:
[[[  1   2   3   4]
  [  5   6 100   8]
  [  9  10  11  12]]

 [[ 13  14  15  16]
  [ 17  18  19  20]
  [ 21  22  23  24]]]


#

In [18]:
# 100. Broadcasting in 3D array

arr = np.arange(1, 25).reshape(2, 3, 4)

print("Original Array:")
print(arr)

original = arr.copy()

# Assign scalar value to complete slice
arr[0, :, :] = 100

print("\nAfter broadcasting 100:")
print(arr)

# Restore original array
arr = original.copy()

print("\nRestored Array:")
print(arr)

Original Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

After broadcasting 100:
[[[100 100 100 100]
  [100 100 100 100]
  [100 100 100 100]]

 [[ 13  14  15  16]
  [ 17  18  19  20]
  [ 21  22  23  24]]]

Restored Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


#
#

## Boolean Indexing and Conditional Selection

#

In [19]:
# 101. Boolean indexing for rows

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

mask = matrix[:, 0] > 3

print("Matrix:")
print(matrix)

print("\nBoolean Mask:")
print(mask)

print("\nSelected Rows:")
print(matrix[mask])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Boolean Mask:
[False  True  True]

Selected Rows:
[[4 5 6]
 [7 8 9]]


#

In [20]:
# 102. Conditional selection

arr = np.array([0.1, 0.3, 0.6, 0.2, 0.8, 0.4])

mask = arr < 0.5

print("Original Array:")
print(arr)

print("\nBoolean Mask:")
print(mask)

print("\nElements less than 0.5:")
print(arr[mask])

print("\nDirect method:")
print(arr[arr < 0.5])

Original Array:
[0.1 0.3 0.6 0.2 0.8 0.4]

Boolean Mask:
[ True  True False  True False  True]

Elements less than 0.5:
[0.1 0.3 0.2 0.4]

Direct method:
[0.1 0.3 0.2 0.4]


#
#

## Shape and Axis Manipulation

#

In [21]:
# 103. Flatten, transpose and reshape

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)

# Flatten using ravel()
flat = arr.ravel()

print("\nFlattened using ravel():")
print(flat)

# Transpose using .T
print("\nTranspose using .T:")
print(arr.T)

# Transpose using transpose()
print("\nTranspose using transpose():")
print(arr.transpose())

# Reshape
reshaped = arr.reshape(3, 2)

print("\nReshaped Array:")
print(reshaped)

Original Array:
[[1 2 3]
 [4 5 6]]

Flattened using ravel():
[1 2 3 4 5 6]

Transpose using .T:
[[1 4]
 [2 5]
 [3 6]]

Transpose using transpose():
[[1 4]
 [2 5]
 [3 6]]

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]


#

In [22]:
# 104. swapaxes()

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)

result = arr.swapaxes(0, 1)

print("\nAfter swapping axes:")
print(result)

print("\nOriginal Shape:")
print(arr.shape)

print("\nNew Shape:")
print(result.shape)

Original Array:
[[1 2 3]
 [4 5 6]]

After swapping axes:
[[1 4]
 [2 5]
 [3 6]]

Original Shape:
(2, 3)

New Shape:
(3, 2)


#
#

## Array Joining (Stacking)

#

In [23]:
# 105. vstack() and hstack()

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Array A:")
print(A)

print("\nArray B:")
print(B)

vertical = np.vstack((A, B))

print("\nVertical Stack:")
print(vertical)

horizontal = np.hstack((A, B))

print("\nHorizontal Stack:")
print(horizontal)

Array A:
[[1 2]
 [3 4]]

Array B:
[[5 6]
 [7 8]]

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


#

In [31]:
# 106. column_stack() and row_stack()

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

column_result = np.column_stack((a, b))
row_result = np.vstack((a, b))

print("Column Stack:")
print(column_result)

print("\nRow Stack:")
print(row_result)

Column Stack:
[[1 4]
 [2 5]
 [3 6]]

Row Stack:
[[1 2 3]
 [4 5 6]]


#
#

## Array Splitting

#

In [25]:
# 107. vsplit() and hsplit()

arr = np.arange(1, 13).reshape(3, 4)

print("Original Array:")
print(arr)

print("\nShape:")
print(arr.shape)

# Vertical split
vertical = np.vsplit(arr, 3)

print("\nVertical Split:")

for part in vertical:
    print(part)
    print("Shape:", part.shape)

# Horizontal split
horizontal = np.hsplit(arr, 2)

print("\nHorizontal Split:")

for part in horizontal:
    print(part)
    print("Shape:", part.shape)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape:
(3, 4)

Vertical Split:
[[1 2 3 4]]
Shape: (1, 4)
[[5 6 7 8]]
Shape: (1, 4)
[[ 9 10 11 12]]
Shape: (1, 4)

Horizontal Split:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Shape: (3, 2)
[[ 3  4]
 [ 7  8]
 [11 12]]
Shape: (3, 2)


#

In [26]:
# 108. Unequal split

arr = np.arange(1, 11)

print("Original Array:")
print(arr)

parts = np.split(arr, [3, 7])

print("\nUnequal Parts:")

for part in parts:
    print(part)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Unequal Parts:
[1 2 3]
[4 5 6 7]
[ 8  9 10]


#
#

## Copy vs View Behavior

#

In [27]:
# 109. Assignment behavior

arr1 = np.array([10, 20, 30, 40])

arr2 = arr1

print("Before modification:")
print("arr1:", arr1)
print("arr2:", arr2)

arr2[0] = 100

print("\nAfter modifying arr2:")
print("arr1:", arr1)
print("arr2:", arr2)

print("\nAre they sharing the same data?")
print(arr1 is arr2)

Before modification:
arr1: [10 20 30 40]
arr2: [10 20 30 40]

After modifying arr2:
arr1: [100  20  30  40]
arr2: [100  20  30  40]

Are they sharing the same data?
True


#

In [28]:
# 110. View vs copy

arr = np.array([10, 20, 30, 40, 50])

# Create a view using slicing
view = arr[1:4]

# Create an independent copy
copy_arr = arr[1:4].copy()

print("Original Array:")
print(arr)

print("\nView:")
print(view)

print("\nCopy:")
print(copy_arr)

# Modify view
view[0] = 100

# Modify copy
copy_arr[1] = 200

print("\nAfter modifications:")

print("Original Array:")
print(arr)

print("\nView:")
print(view)

print("\nCopy:")
print(copy_arr)

Original Array:
[10 20 30 40 50]

View:
[20 30 40]

Copy:
[20 30 40]

After modifications:
Original Array:
[ 10 100  30  40  50]

View:
[100  30  40]

Copy:
[ 20 200  40]


#
#

## Vectorization and Performance

#

In [29]:
# 111. Vectorized multiplication

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

result = a * b

print("Array A:")
print(a)

print("\nArray B:")
print(b)

print("\nVectorized Multiplication:")
print(result)

Array A:
[1 2 3 4 5]

Array B:
[10 20 30 40 50]

Vectorized Multiplication:
[ 10  40  90 160 250]


#

In [30]:
# 112. Compare loop-based and vectorized operations

import time

a = np.arange(1000000)
b = np.arange(1000000)

# Loop-based multiplication
start = time.time()

result_loop = np.empty(len(a))

for i in range(len(a)):
    result_loop[i] = a[i] * b[i]

loop_time = time.time() - start


# Vectorized multiplication
start = time.time()

result_vectorized = a * b

vectorized_time = time.time() - start


print("Loop-based time:", loop_time, "seconds")
print("Vectorized time:", vectorized_time, "seconds")

print("\nLoop Result:")
print(result_loop[:10])

print("\nVectorized Result:")
print(result_vectorized[:10])

print("\nSpeedup:")
print(loop_time / vectorized_time)

Loop-based time: 0.2951970100402832 seconds
Vectorized time: 0.0023126602172851562 seconds

Loop Result:
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]

Vectorized Result:
[ 0  1  4  9 16 25 36 49 64 81]

Speedup:
127.64391752577319
